version: '3.7'

services:
  storage_1:
    build:
      context: .
      dockerfile: Dockerfile-nginx
    ports:
      - "5002:80"

  storage_redis_1:
    image: redis:5.0
    volumes:
      - storage_redis_1_data:/data

volumes:
  storage_redis_1_data: